name: Test workflow

on:
  push:
    branches:
      # Trigger when code is pushed to any branch on this repository
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print the variables and secrets
        env:
          VARIABLES_ALL: ${{ toJSON(vars) }}
          SECRETS_ALL: ${{ toJSON(secrets) }}
        run: |
          echo "$VARIABLES_ALL"
          echo "$SECRETS_ALL" 


